name: Update dstool package

jobs:
  update-dstool:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Clone repository
        run: |
          mkdir github
          cd github
          git clone https://github.com/ydb-platform/ydb.git
          cd ydb
          ydb_root=$(pwd)

      - name: Compile proto files and build package
        run: |
          cd ${{ github.workspace }}/github/ydb
          ./ydb/apps/dstool/compile_protos.py --ydb-root ./ 2>/dev/null
          mv ydb/apps/dstool/setup.py .
          python -m build

      - name: Upload package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          cd ${{ github.workspace }}/github/ydb
          python -m twine upload dist/*
